name: taiwan_lottery
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  barcode_scan: ^0.0.7
  cupertino_icons: ^0.1.2
  http: ^0.12.0
flutter:
  uses-material-design: true
